name: ci

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: urlshorty
        ports:
          - "5432:5432"
        options: >-
          --health-cmd="pg_isready -U postgres" --health-interval=5s
      redis:
        image: redis:7
        ports:
          - "6379:6379"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - name: Run Alembic migrations
        env:
          DATABASE_URL: postgresql+psycopg://postgres:postgres@localhost:5432/urlshorty
        run: alembic upgrade head
      - env:
          DATABASE_URL: postgresql+psycopg://postgres:postgres@localhost:5432/urlshorty
          REDIS_URL: redis://localhost:6379/0
        run: pytest -q
